### PR TITLE
check parent directories for .git folder

### PR DESCRIPTION
**Pull request by hellatan**
fixed merge conflict as well

### CODE REVIEW

**Comment by hellatan** [comment]
@twhid it looks like i don't have write access to this repo. 

Can we get this merged and then we can publish this to our internal npm to use the "one up" functionality?

cc @robrichard

**Comment by twhid** [comment]
@hellatan you should have write access now.

**Comment by robrichard** [comment]
👍

**Comment by hellatan** [comment]
```
daletan:~/projects/pre-commit (master)
$ npm publish
+ dibs-pre-commit@2.0.0
```

**Pull request merged**
